<?php

/**
 * 
 * 1. $mysqli -> affected_rows | mysqli_affected_rows(connection) 
 * 2. $mysqli -> autocommit(mode) | mysqli_autocommit(connection, mode)
 * 3. $mysqli -> change_user(username, password, dbname) | mysqli_change_user(connection, username, password, dbname) 
 * 4. $mysqli -> character_set_name() | mysqli_character_set_name(connection) 
 * 5. $mysqli -> close() | mysqli_close(connection)
 * 6. $mysqli -> commit(flags, name) | mysqli_commit(connection, flags, name) 
 * 7. $mysqli -> new mysqli(host, username, password, dbname, port, socket) | mysqli_connect(host, username, password, dbname, port, socket) 
 * 8. $mysqli -> connect_errno | mysqli_connect_errno()
 * 9. $mysqli -> connect_error | mysqli_connect_error();
 * 10. mysqli_data_seek(result,offset);
 * 11. mysqli_debug(message);
 * 12. $mysqli -> dump_debug_info() | mysqli_dump_debug_info(link); 
 * 13. $mysqli -> errno | mysqli_errno(connection) 
 * 14. $mysqli -> error | mysqli_error(connection) 
 * 15. $mysqli -> error_list | mysqli_error_list(connection)
 * 16. $mysqli_result -> fetch_all(resulttype) | mysqli_fetch_all(result, resulttype) 
 * 17. $mysqli_result -> fetch_array(resulttype) | mysqli_fetch_array(result,resulttype) 
 * 18. $mysqli_result -> fetch_assoc() | mysqli_fetch_assoc(result)
 * 19. $mysqli_result -> fetch_field() | mysqli_fetch_field(result)
 * 20. $mysqli_result -> fetch_field_direct(fieldnr) | mysqli_fetch_field_direct(result, fieldnr)
 * 21. $mysqli_result -> fetch_fields() | mysqli_fetch_fields(result)
 * 22. $mysqli_result -> lengths | mysqli_fetch_lengths(result) 
 * 23. $mysqli_result -> fetch_object(classname, params) | mysqli_fetch_object(result, classname, params) 
 * 24. $mysqli_result -> fetch_row() | mysqli_fetch_row(result)
 * 25. $mysqli -> field_count() | mysqli_field_count(connection)
 * 26. $mysqli_result -> field_seek(fieldnr) | mysqli_field_seek(result, fieldnr)
 * 27. $mysqli -> get_charset() | mysqli_get_charset(connection);
 * 28. $mysqli -> get_client_info() | mysqli_get_client_info(connection) 
 * 29. mysqli_get_client_stats()  
 * 30. $mysqli -> client_version | mysqli_get_client_version(connection) 
 * 31. $mysqli -> get_connection_stats() | mysqli_get_connection_stats(connection) 
 * 32. $mysqli -> host_info | mysqli_get_host_info(connection) 
 * 33. $mysqli -> protocol_version | mysqli_get_proto_info(connection)
 * 34. $mysqli -> server_info | mysqli_get_server_info(connection)
 * 35. $mysqli -> server_version | mysqli_get_server_version(connection)
 * 36. $mysqli -> info | mysqli_info(connection)
 * 37. $mysqli -> init | mysqli_init() 
 * 38. $mysqli -> insert_id | mysqli_insert_id(connection)
 * 39. $mysqli -> kill(processid) | mysqli_kill(connection, processid) 
 * 40. $mysqli -> more_results() | mysqli_more_results(connection) 
 * 41. $mysqli -> multi_query(query) | mysqli_multi_query(connection, query)
 * 42. $mysqli -> next_result() | mysqli_next_result(connection); 
 * 43. $mysqli -> options(option, value) | mysqli_options(connection, option, value) 
 * 44. $mysqli -> ping() | mysqli_ping(connection)
 * 45. $mysqli -> poll(read, error, reject, seconds, microseconds) | mysqli_poll(read, error, reject, seconds, microseconds) 
 * 46. $mysqli -> prepare(query) | mysqli_prepare(connection, query)
 * 47. $mysqli -> query(query, resultmode) | mysqli_query(connection, query, resultmode)
 * 48. $mysqli -> real_connect(host, username, password, dbname, port, socket, flag) | mysqli_real_connect(connection, host, username, password, dbname, port, socket, flag)
 * 49. $mysqli -> real_escape_string(escapestring) | mysqli_real_escape_string(connection, escapestring)
 * 50. $mysqli -> real_query(query) | mysqli_real_query(connection, query)
 * 51. $mysqli -> reap_async_query() | mysqli_reap_async_query(connection)
 * 52. $mysqli -> refresh(options) | mysqli_refresh(connection, options)
 * 53. $mysqli -> rollback(flags, name) | mysqli_rollback(connection, flags, name)
 * 54. $mysqli -> select_db(name) | mysqli_select_db(connection, name)
 * 55. $mysqli -> set_charset(charset) | mysqli_set_charset(connection, charset) 
 * 56. $mysqli -> set_local_infile_handler(read_file) | mysqli_set_local_infile_handler(read_file)
 * 57. $mysqli -> sqlstate | mysqli_sqlstate(connection)
 * 58. $mysqli -> ssl_set(key, cert, ca, capath, cipher) | mysqli_ssl_set(connection, key, cert, ca, capath, cipher)
 * 59. $mysqli -> stat() | mysqli_stat(connection)
 * 60. $mysqli -> stmt_init() | mysqli_stmt_init(connection)
 * 61. $mysqli -> thread_id() | mysqli_thread_id(connection)
 * 62. mysqli_thread_safe()
 * 63. $mysqli -> use_result() | mysqli_use_result(connection)
 * 64. $mysqli -> warning_count | mysqli_warning_count(connection)
 */